If you use the RecipientInformation.getContent(recipient) method instead of the deprecated RecipientInformation.getContent(key, provider) method, the Java ClassLoader needs to load the Recipient.class file and for obvious reasons this results in a NoClassDefFoundError if the BC jars aren't in the CLASSPATH. However: we don't want to force people to have the BC jars in their CLASSPATH if no encryption or digital signing is involved. Further investigation of the RecipientInformation class is needed before we can replace the deprecated version of the getContent() method.
git-svn-id: https://svn.code.sf.net/p/itext/code/trunk@5131 3a709846-db2a-4fbd-be0b-eb932eee6479